# ??????
ruoyi:
  # ??
  name: 静心栖

  version: 3.8.8

  copyrightYear: 2025

  profile: D:/ruoyi/uploadPath
  # ??ip????
  addressEnabled: false
  # ????? math ???? char ????
  captchaType: math

# ??????
server:
  # ????HTTP??????8080
  port: 9901
  servlet:
    # ???????
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # ?????????????100
    accept-count: 1000
    threads:
      # tomcat?????????200
      max: 800
      # Tomcat?????????????10
      min-spare: 100

# ????
logging:
  level:
    com.zzyl: debug
    org.springframework: warn

# ????
user:
  password:
    # ????????
    maxRetryCount: 5
    # ?????????10???
    lockTime: 10

# Spring??
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # ?????
      master:
        url: jdbc:mysql://localhost:3306/zzyl?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 1234
      # ?????
      slave:
        # ??????/????
        enabled: false
        url:
        username:
        password:
      # ?????
      initialSize: 5
      # ???????
      minIdle: 10
      # ???????
      maxActive: 20
      # ?????????????
      maxWait: 60000
      # ????????
      connectTimeout: 30000
      # ????????
      socketTimeout: 60000
      # ???????????????????????????????
      timeBetweenEvictionRunsMillis: 60000
      # ??????????????????????
      minEvictableIdleTimeMillis: 300000
      # ??????????????????????
      maxEvictableIdleTimeMillis: 900000
      # ??????????
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # ???????????????
        allow:
        url-pattern: /druid/*
        # ???????????
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # ?SQL??
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # ????
  messages:
    # ?????????
    basename: i18n/messages
  # ????
  servlet:
    multipart:
      # ??????
      max-file-size: 10MB
      # ??????????
      max-request-size: 20MB
  # ????
  devtools:
    restart:
      # ?????
      enabled: true
  # redis ??
  redis:
    # ??
    host: 127.0.0.1
    # ??????6379
    port: 6379
    # ?????
    database: 0
    # ??
#    password: 123456
    # ??????
    timeout: 10s
    lettuce:
      pool:
        # ???????????
        min-idle: 0
        # ???????????
        max-idle: 8
        # ????????????
        max-active: 8
        # #???????????????????????
        max-wait: -1ms

# token??
token:
  # ???????
  header: Authorization
  # ????
  secret: abcdefghijklmnopqrstuvwxyz
  # ????????30???
  expireTime: 30

# MyBatisPlus??
mybatis-plus:
  # ???????
  typeAliasesPackage: com.zzyl.**.domain
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # ????
  global-config:
    db-config:
      id-type: auto   #id???????
  configuration:
    map-underscore-to-camel-case: true    #???????????????

# PageHelper????
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger??
swagger:
  # ????swagger
  enabled: true
  # ????
  pathMapping: /dev-api

# ??XSS??
xss:
  # ????
  enabled: true
  # ?????????????
  excludes: /system/notice
  # ????
  urlPatterns: /system/*,/monitor/*,/tool/*
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: ${OSS_ACCESS_KEY_ID}
  accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
  bucketName: cytzznursing
deepseek:
  baseUrl: https://api.deepseek.com/chat/completions
  apiKey: ${DEEPSEEK_API_KEY}
  model: deepseek-chat
wechat:
  appid: wxa54e0997e8b6649e
  secret: ${WECHAT_SECRET}
nursingId: 201
